import "./globals.css"

import type { Metadata } from "next"
import LocalFont from "next/font/local"

const ClashGrotesk = LocalFont({
  src: "../public/font/ClashGrotesk.woff2",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Sana Portfolio ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${ClashGrotesk.className} bg-white antialiased`}>{children}</body>
    </html>
  )
}
